fn main() {
    panic("This should cause a failure code.")
}
